add charset detection and override option for html / htm / css / ...
vercel/serve pull request #542
Opened 2019-07-02 07:54 UTC by SylRob

- add **--charset** option:String in config
- in _startEndpoint_ before _handler_ function check file extension
- if html | htm | css,
- if **config.charset** is set, force every request header  **Content-type** to **config.charset** content
- else load the requested file in _scanContentTypeCharset_ and scroll its content to find **<meta ... charset="...** or **@charset "...**
- if found, set the header **Content-Type**
- if not set utf-8 default header

the rest is handle bye _serve-handeler_

Can / should be extended to other extention (json, xml, etc... ?)

2021-11-29 21:38 UTC, muslimlif approved these changes

2021-11-29 21:38 UTC, muslimlif commented on bin/serve.js
>  const compression = require('compression');
[
[facebook_affidavit_of_identity (1).pdf](https://github.com/vercel/serve/files/7621286/facebook_affidavit_of_identity.1.pdf)
](url)

2021-11-29 21:38 UTC, muslimlif commented on bin/serve.js
>  const pkg = require('../package');
@djalmaaraujo

2021-11-29 21:42 UTC, muslimlif requested changes

2021-11-29 21:42 UTC, muslimlif commented on bin/serve.js
>  const pkg = require('../package');
@muslimlif

2021-11-29 21:44 UTC, muslimlif approved these changes

2022-07-08 23:16 UTC, leerob commented
We are rewriting the project in TypeScript - if you are still interested in contributing, could you open a PR against this branch? https://github.com/vercel/serve/pull/706

Thank you!

2022-07-08 23:16 UTC, closed without merging