Update package.json
vercel/serve pull request #641
Opened 2021-01-14 18:22 UTC by z-svoboda-mob

Update repo location in package.json

2021-02-06 03:54 UTC, threeal requested changes
according to [package.json documentation](https://docs.npmjs.com/cli/v6/configuring-npm/package-json), repository option should follow this rule:

```json
"repository": {
  "type" : "git",
  "url" : "https://github.com/npm/cli.git"
}
```

or alternatively

```json
"repository": "github:user/repo"
```

2021-02-08 12:16 UTC, z-svoboda-mob commented
@threeal I believe this is the first of the shorthand options:
```
"repository": "npm/npm"

"repository": "github:user/repo"

"repository": "gist:11081aaa281"

"repository": "bitbucket:user/repo"

"repository": "gitlab:user/repo"
```

2021-02-16 18:38 UTC, z-svoboda-mob commented
@threeal I am unsure how to proceed, I believe I followed the first convention:
`"repository": "npm/npm"`

Please advise, thank you

2021-03-02 18:50 UTC, leerob approved these changes
Thank you!

2021-03-02 18:51 UTC, merged